import type { OrganizationProfile } from '../../../../shared/types';

export const HARDCODED_PROFILE: OrganizationProfile = {
  legalName: 'Hacker Dojo, a California nonprofit corporation',
  ein: '26-4812213',
  samUEI: '',
  nonprofitStatus: '501(c)(3)',
  contactInfo: {
    phone: '(650) 429-8605',
    website: 'https://hackerdojo.org',
    address: '855 Maude Ave, Mountain View, CA 94043',
  },
  geography: 'San Francisco Bay Area / Silicon Valley',
  mission:
    'Hacker Dojo is a collaborative hackerspace where tech enthusiasts gather to build, experiment, and improve. A community-driven makerspace and coworking hub in Mountain View, California, providing equitable access to tools, mentorship, and collaborative learning for hackers, makers, builders, and lifelong learners.',
  programAreas: [
    'Makerspace operations (hardware labs, 3D printing, maker tools)',
    'AI literacy and emerging technology education',
    'AI Career Initiative (career pivot and upskilling program)',
    'AI Stars program',
    'Startup Accelerator',
    'Summer Camp (youth STEM education)',
    'Community innovation and entrepreneurship',
    'Workforce development and STEM equity',
    'Informal STEM learning',
    'Digital inclusion and technology access',
    'Hackathons and technical workshops',
    'Hack Comedy Night and community events',
  ],
  populationsServed: [
    'First-generation learners and career-changers',
    'Women and underrepresented groups in tech',
    'Returning workers and career-transitioners',
    'Non-native English speakers',
    'Bay Area residents',
    'Students and lifelong learners',
    'Startup founders and entrepreneurs',
    'Veterans (dedicated membership tier)',
  ],
  partnerships: [
    'Mountain View Public Library',
    'Foothill-De Anza Community College District',
    'Code2College',
    'Local makerspaces and hackerspaces',
    'Meetup.com (events platform)',
    'Every.org (donation processing)',
  ],
  fundingHistory: [
    {
      year: 2025,
      amount: 0,
      source: 'Community memberships (~$150/mo standard)',
      purpose: 'Operational funding',
    },
    {
      year: 2025,
      amount: 0,
      source: 'Corporate and individual donations',
      purpose: 'Expansion and equipment',
    },
  ],
  complianceFacts: [
    '501(c)(3) verified — IRS confirmation on file (EIN 26-4812213)',
    'California Secretary of State — active nonprofit',
    'Founded 2009 — 17-year track record',
    'Policies published at wiki.hackerdojo.com',
  ],
  docTypes: ['PDF', 'DOCX', 'XLSX', 'CSV'],
  searchThemes: [
    'Makerspaces and hackerspaces',
    'AI literacy and trustworthy AI',
    'Community innovation hubs',
    'Workforce development',
    'STEM equity and informal STEM',
    'Digital inclusion',
    'Bay Area / Silicon Valley',
    'Equipment and capital investment',
    'Capacity building for nonprofits',
    'Youth STEM education and summer camps',
    'Startup accelerators and entrepreneurship',
    'Veteran career transition programs',
  ],
  agentBehavior: {
    autoDraftThreshold: 75,
    submissionPolicy: 'Human approval required — agent never submits',
    notifyEmail: 'ed@hackerdojo.com',
    voiceAndTone:
      'Plain-spoken, evidence-led, builder-community framing. Avoid jargon. Lead with outcomes. Reference Hacker Dojo\'s 17-year track record (founded 2009), 4,200+ members, 380+ annual events, hardware labs, and impact metrics from the Impact Report.',
  },
};
