import fs from 'node:fs/promises';
import path from 'node:path';
import { expect, test, type APIRequestContext } from '@playwright/test';
import { resetAppState } from './test-utils';

const fixturePath = path.join(
  process.cwd(),
  'tests/fixtures/documents/hacker-dojo-program-summary.pdf',
);
const opencodeStubPath = path.join(process.cwd(), 'tests/e2e/opencode-stub.sh');
const exactSentence =
  'Hacker Dojo expands access to technology education and community innovation in Silicon Valley.';

async function ensureOpencodeStub(): Promise<string> {
  const script = `#!/bin/sh
cat <<'EOF'
## Hacker Dojo Grant Proposal

Hacker Dojo expands access to technology education and community innovation in Silicon Valley.

This draft is generated by the E2E stub and includes the grounded sentence exactly once.
EOF
`;
  await fs.writeFile(opencodeStubPath, script, 'utf8');
  await fs.chmod(opencodeStubPath, 0o755);
  return opencodeStubPath;
}

async function configureOpencode(api: APIRequestContext, binaryPath: string): Promise<void> {
  const response = await api.put('http://localhost:3000/api/opencode-settings', {
    data: {
      binaryPath,
      workingDirectory: process.cwd(),
      timeoutMs: 60000,
      profile: 'default',
      isConfigured: true,
    },
  });
  expect(response.ok()).toBeTruthy();
}

test('document-grounded-drafting: upload, ground, draft, approve, revise, and submit', async ({
  page,
  request,
}) => {
  const stubPath = await ensureOpencodeStub();

  await resetAppState(request);
  await configureOpencode(request, stubPath);
  await page.goto('http://localhost:3000');
  await page.waitForSelector('.app', { timeout: 10000 });

  await request.patch('http://localhost:3000/api/grants/nsf-techaccess', {
    data: {
      status: 'draft',
      statusLabel: 'Drafting',
      draftContent: '',
    },
    headers: { 'Content-Type': 'application/json' },
  });

  const bytes = await fs.readFile(fixturePath);
  const uploadResult = await page.evaluate(async ({ base64, exact }) => {
    const binary = Uint8Array.from(atob(base64), (char) => char.charCodeAt(0));
    const formData = new FormData();
    formData.append('name', 'Hacker Dojo Program Summary');
    formData.append('type', 'PDF');
    formData.append('file', new File([binary], 'hacker-dojo-program-summary.pdf', { type: 'application/pdf' }));

    const response = await fetch('http://localhost:3000/api/documents', {
      method: 'POST',
      body: formData,
    });

    const text = await response.text();
    return { ok: response.ok, status: response.status, text, exact };
  }, { base64: bytes.toString('base64'), exact: exactSentence });

  if (!uploadResult.ok) {
    throw new Error(`Upload failed with status ${uploadResult.status}: ${uploadResult.text}`);
  }
  expect(uploadResult.status).toBe(201);
  const uploadedDocument = JSON.parse(uploadResult.text) as { extractionStatus?: string; contentSnippet?: string };
  expect(uploadedDocument.extractionStatus).toBe('extracted');
  expect(uploadedDocument.contentSnippet).toBe(exactSentence);

  const draftResponse = await request.post(
    'http://localhost:3000/api/grants/nsf-techaccess/draft',
    {
      headers: { 'Content-Type': 'application/json' },
      data: { revisionNotes: 'Ground the draft in the uploaded PDF.' },
    },
  );
  expect(draftResponse.ok()).toBeTruthy();
  const draft = await draftResponse.json();
  expect(draft.content).toContain(exactSentence);

  const approvalResponse = await request.post(
    'http://localhost:3000/api/grants/nsf-techaccess/approval',
    {
      headers: { 'Content-Type': 'application/json' },
      data: { approvedBy: 'Playwright' },
    },
  );
  expect(approvalResponse.ok()).toBeTruthy();

  const revisionResponse = await request.post(
    'http://localhost:3000/api/grants/nsf-techaccess/revisions',
    {
      headers: { 'Content-Type': 'application/json' },
      data: { notes: 'Please tighten the budget section and keep the grounding sentence.' },
    },
  );
  expect(revisionResponse.ok()).toBeTruthy();
  const revision = await revisionResponse.json();
  expect(revision.draft.content).toContain(exactSentence);

  const reapprovalResponse = await request.post(
    'http://localhost:3000/api/grants/nsf-techaccess/approval',
    {
      headers: { 'Content-Type': 'application/json' },
      data: { approvedBy: 'Playwright' },
    },
  );
  expect(reapprovalResponse.ok()).toBeTruthy();

  const submitResponse = await request.post(
    'http://localhost:3000/api/grants/nsf-techaccess/submit',
    {
      headers: { 'Content-Type': 'application/json' },
      data: {
        method: {
          type: 'email',
          confirmationId: `PW-${Date.now()}`,
          submittedBy: 'Playwright',
        },
        notes: 'Submitted from E2E grounded drafting flow',
      },
    },
  );
  expect(submitResponse.ok()).toBeTruthy();
  const submit = await submitResponse.json();
  expect(submit.followUps.length).toBeGreaterThan(0);

  await page.goto('http://localhost:3000');
  await page.waitForSelector('.app', { timeout: 10000 });
  await page.reload();
  await page.waitForSelector('.app', { timeout: 10000 });

  await expect(page.locator('.nav-item:has-text("Notifications") .nav-count').first()).toBeVisible();
  await expect(page.locator('.nav-item:has-text("Tasks") .nav-count').first()).toBeVisible();
  await expect(page.locator('.sidebar-footer')).toContainText('Logged in as');
});
