import fs from 'node:fs/promises';
import path from 'node:path';
import {
	type APIRequestContext,
	expect,
	type Page,
	test,
} from '@playwright/test';
import { resetAppState } from './test-utils';

const fixturePath = path.join(
	process.cwd(),
	'tests/fixtures/documents/hacker-dojo-program-summary.pdf',
);
const opencodeStubPath = path.join(process.cwd(), 'tests/e2e/opencode-stub.sh');

async function ensureOpencodeStub(): Promise<string> {
	const script = `#!/bin/sh
set -eu

all_args="$*"
json_output=0
case "$all_args" in
	*"Research grants for the following organization:"*|*"--output-format json"*|*"--format json"*)
		json_output=1
		;;
esac

if [ "$json_output" -eq 1 ]; then
	cat <<'EOF'
{"grants":[{"id":"stub-grant-001","title":"Education Technology Community Grant","funder":"Mock Foundation","funderShort":"Mock","award":"$50,000","awardSort":50000,"deadline":"2026-06-30","daysOut":30,"fit":82,"tags":["EdTech","Community"],"status":"matched","statusLabel":"Matched","matchedAt":"2026-05-24T00:00:00.000Z"},{"id":"stub-grant-002","title":"Community Innovation Grant","funder":"Alliance for Learning","funderShort":"Alliance","award":"$75,000","awardSort":75000,"deadline":"2026-07-15","daysOut":45,"fit":76,"tags":["Community","Innovation"],"status":"matched","statusLabel":"Matched","matchedAt":"2026-05-24T00:00:00.000Z"}],"evidence":[{"id":"stub-evidence-001","grantId":"stub-grant-001","sourceId":"stub-source-001","sourceName":"Stub Source","evidenceType":"eligibility","content":"Community alignment evidence","capturedAt":"2026-05-24T00:00:00.000Z"}],"rationale":"E2E research stub response"}
EOF
else
	cat <<'EOF'
## Hacker Dojo Grant Proposal

Hacker Dojo expands access to technology education and community innovation in Silicon Valley.

This draft is generated by the E2E stub and includes the grounded sentence exactly once.
EOF
fi
`;
	await fs.writeFile(opencodeStubPath, script, 'utf8');
	await fs.chmod(opencodeStubPath, 0o755);
	return opencodeStubPath;
}

async function configureProfile(api: APIRequestContext): Promise<void> {
	const response = await api.put('http://localhost:3000/api/profile', {
		data: {
			legalName: 'Hacker Dojo',
			ein: '26-3375350',
			samUEI: 'XK7N4HQ2P3M9',
			mission: 'Community innovation and education',
			docTypes: ['PDF'],
			searchThemes: ['EdTech', 'Community'],
			agentBehavior: {
				autoDraftThreshold: 75,
				submissionPolicy: 'Human approval required',
				notifyEmail: 'ed@hackerdojo.com',
				voiceAndTone: 'Plain-spoken',
			},
		},
	});
	expect(response.ok()).toBeTruthy();
}

async function configureOpencode(
	api: APIRequestContext,
	binaryPath: string,
): Promise<void> {
	const response = await api.put('http://localhost:3000/api/opencode-settings', {
		data: {
			binaryPath,
			workingDirectory: process.cwd(),
			timeoutMs: 60000,
			profile: 'default',
			isConfigured: true,
		},
	});
	expect(response.ok()).toBeTruthy();
}

async function uploadGroundingDocument(api: APIRequestContext): Promise<void> {
	const bytes = await fs.readFile(fixturePath);
	const uploadResponse = await api.post('http://localhost:3000/api/documents', {
		multipart: {
			name: 'Hacker Dojo Program Summary',
			type: 'PDF',
			file: {
				name: 'hacker-dojo-program-summary.pdf',
				mimeType: 'application/pdf',
				buffer: bytes,
			},
		},
	});
	expect(uploadResponse.ok()).toBeTruthy();
}

async function openMatchedGrantWithoutDraft(
	page: Page,
	request: APIRequestContext,
) {
	const grantsResponse = await request.get('http://localhost:3000/api/grants');
	expect(grantsResponse.ok()).toBeTruthy();
	const grants: Array<{
		id: string;
		title: string;
		fit: number;
		status: string;
		draftContent?: string;
		funder: string;
	}> = await grantsResponse.json();

	const targetGrant = grants.find(
		(grant) => grant.status === 'matched' && !grant.draftContent,
	);
	expect(targetGrant).toBeDefined();
	if (!targetGrant) {
		throw new Error('Expected a matched grant without draft content');
	}

	const sortedGrants = [...grants].sort((a, b) => b.fit - a.fit);
	const selectedIndex = sortedGrants.findIndex(
		(grant) => grant.id === targetGrant.id,
	);
	expect(selectedIndex).toBeGreaterThan(-1);

	await page.click('[data-view="discovery"]');
	await page.locator('.grants-row:not(.header)').nth(selectedIndex).click();
	await expect(page.locator('.drawer-title')).toHaveText(targetGrant.title);
	return targetGrant;
}

test.describe('Submission Notification', () => {
	test.beforeEach(async ({ page, request }) => {
		await page.goto('http://127.0.0.1:3000');
		await page.waitForSelector('.app', { timeout: 10000 });
		await resetAppState(request);
		await page.reload();
		await page.waitForSelector('.app', { timeout: 10000 });
	});

	test('notify-email-is-configured: notifyEmail is set in profile', async ({
		page,
	}) => {
		const profile = await page.evaluate(async () => {
			const response = await fetch('/api/profile');
			return { status: response.status, body: await response.json() };
		});

		expect(profile.status).toBe(200);
		expect(profile.body.agentBehavior).toBeDefined();
		expect(profile.body.agentBehavior.notifyEmail).toBeDefined();
		expect(profile.body.agentBehavior.notifyEmail.length).toBeGreaterThan(0);
		expect(profile.body.agentBehavior.notifyEmail).toMatch(
			/^[^\s@]+@[^\s@]+\.[^\s@]+$/,
		);
	});

	test('approval-submission-artifacts: approve, submit, and surface follow-up artifacts', async ({
		page,
		request,
	}) => {
		const stubPath = await ensureOpencodeStub();
		await configureProfile(request);
		await configureOpencode(request, stubPath);
		await uploadGroundingDocument(request);

		const targetGrant = await openMatchedGrantWithoutDraft(page, request);

		await expect(page.locator('button:has-text("Generate draft")')).toBeVisible();
		await page.getByRole('button', { name: 'Generate draft' }).click();
		await expect(page.locator('.draft-preview')).toContainText(
			'Hacker Dojo expands access to technology education and community innovation in Silicon Valley.',
		);
		await expect(page.locator('.ai-badge')).toContainText('Drafted by agent');

		await page.getByRole('button', { name: 'Approve & lock' }).click();
		await expect(page.locator('.drawer-actions')).toContainText('Submit');

		await page.locator('.drawer-actions').getByRole('button', { name: 'Submit' }).click();
		await page
			.locator('.drawer-section')
			.filter({ hasText: 'Submit grant' })
			.locator('select')
			.selectOption('email');
		await page
			.locator('input[placeholder="Confirmation ID"]')
			.fill(`PW-${Date.now()}`);
		await page
			.locator('textarea[placeholder="Submission notes"]')
			.fill('Submitted from the drawer workflow');
		await page
			.locator('.drawer-section')
			.filter({ hasText: 'Submit grant' })
			.getByRole('button', { name: 'Submit' })
			.click();

		const grantDetailResponse = await request.get(
			`http://localhost:3000/api/grants/${targetGrant.id}`,
		);
		expect(grantDetailResponse.ok()).toBeTruthy();
		const grantDetail = await grantDetailResponse.json();
		expect(grantDetail.grant.status).toBe('submitted');
		expect(grantDetail.submissionRecord?.grantId).toBe(targetGrant.id);
		expect(Array.isArray(grantDetail.followUps)).toBe(true);
		expect(grantDetail.followUps.length).toBeGreaterThan(0);

		const followUpsResponse = await request.get('http://localhost:3000/api/follow-ups');
		expect(followUpsResponse.ok()).toBeTruthy();
		const followUps = (await followUpsResponse.json()) as Array<{ grantId?: string; submissionId?: string; title: string }>;
		expect(followUps.some((followUp) => followUp.grantId === targetGrant.id)).toBe(true);

		const notificationsResponse = await request.get('http://localhost:3000/api/notifications');
		expect(notificationsResponse.ok()).toBeTruthy();
		const notifications = (await notificationsResponse.json()) as Array<{ text: string }>;
		expect(notifications.some((notification) => /Email submission sent to/i.test(notification.text))).toBe(true);

		const tasksResponse = await request.get('http://localhost:3000/api/tasks');
		expect(tasksResponse.ok()).toBeTruthy();
		const tasks = (await tasksResponse.json()) as Array<{ text: string; completed: boolean }>;
		expect(tasks.some((task) => /Follow up on email submission/i.test(task.text))).toBe(true);

		await page.click('[data-view="notifications"]');
		await expect(page.locator('body')).toContainText('Email submission sent to');

		await page.click('[data-view="tasks"]');
		await expect(page.locator('body')).toContainText('Follow up on email submission');
	});
});
