import type { FunderProfile, SavedSearch, Source, CrawlSchedule } from './types';

export const SEED_FUNDERS: FunderProfile[] = [
  {
    id: 'funder-nsf',
    name: 'National Science Foundation (NSF)',
    type: 'government',
    ein: '36-1080746',
    givingHistory: [
      { year: 2023, totalGiving: 9540000000, grantsCount: 12000, averageGrantSize: 795000 },
      { year: 2024, totalGiving: 9060000000, grantsCount: 11500, averageGrantSize: 787000 },
      { year: 2025, totalGiving: 9100000000, grantsCount: 11300, averageGrantSize: 805000 },
    ],
    focusAreas: ['STEM education', 'computer science', 'AI research', 'workforce development', 'informal STEM learning', 'cybersecurity'],
    geographicFocus: ['United States'],
    typicalAwardRange: { min: 50000, max: 3000000 },
    applicationProcess: 'NSF funding opportunities via grants.gov. Proposals submitted through Research.gov or Grants.gov. Requires SAM.gov registration.',
    deadlines: 'Varies by program. Major deadlines typically in January, July, and October.',
    sourceUrls: ['https://nsf.gov', 'https://grants.gov'],
    lastUpdated: '2026-05-30T00:00:00Z',
  },
  {
    id: 'funder-google',
    name: 'Google.org',
    type: 'corporate',
    ein: '77-0047047',
    givingHistory: [
      { year: 2023, totalGiving: 356000000, grantsCount: 250, averageGrantSize: 1424000 },
      { year: 2024, totalGiving: 400000000, grantsCount: 280, averageGrantSize: 1428000 },
      { year: 2025, totalGiving: 450000000, grantsCount: 300, averageGrantSize: 1500000 },
    ],
    focusAreas: ['AI literacy', 'digital inclusion', 'STEM education', 'economic opportunity', 'crisis response'],
    geographicFocus: ['Global', 'Bay Area priority'],
    typicalAwardRange: { min: 100000, max: 5000000 },
    applicationProcess: 'Google.org typically identifies partners directly rather than accepting unsolicited proposals. Expressions of interest through Google.org website.',
    deadlines: 'Rolling',
    sourceUrls: ['https://google.org'],
    lastUpdated: '2026-05-30T00:00:00Z',
  },
  {
    id: 'funder-knight',
    name: 'Knight Foundation',
    type: 'foundation',
    ein: '65-0467711',
    givingHistory: [
      { year: 2023, totalGiving: 165000000, grantsCount: 380, averageGrantSize: 434000 },
      { year: 2024, totalGiving: 175000000, grantsCount: 400, averageGrantSize: 437500 },
      { year: 2025, totalGiving: 180000000, grantsCount: 410, averageGrantSize: 439000 },
    ],
    focusAreas: ['community innovation', 'technology in communities', 'digital literacy', 'journalism', 'arts'],
    geographicFocus: ['United States', 'San Jose (CA)', 'Detroit (MI)', 'Miami (FL)', 'St. Paul (MN)'],
    typicalAwardRange: { min: 50000, max: 5000000 },
    applicationProcess: 'Knight accepts grant inquiries via their online portal. They prioritize organizations in their focus communities.',
    deadlines: 'Rolling; applications accepted year-round',
    sourceUrls: ['https://knightfoundation.org'],
    lastUpdated: '2026-05-30T00:00:00Z',
  },
  {
    id: 'funder-sloan',
    name: 'Alfred P. Sloan Foundation',
    type: 'foundation',
    ein: '13-1639044',
    givingHistory: [
      { year: 2023, totalGiving: 3100000000, grantsCount: 520, averageGrantSize: 5961000 },
      { year: 2024, totalGiving: 3200000000, grantsCount: 500, averageGrantSize: 6400000 },
      { year: 2025, totalGiving: 3000000000, grantsCount: 480, averageGrantSize: 6250000 },
    ],
    focusAreas: ['science and technology', 'economics', 'digital technology', 'energy and environment', 'STEM higher education'],
    geographicFocus: ['United States'],
    typicalAwardRange: { min: 100000, max: 10000000 },
    applicationProcess: 'Letter of inquiry via Sloan website. Full proposals by invitation only.',
    deadlines: 'Rolling; LOIs reviewed quarterly',
    sourceUrls: ['https://sloan.org'],
    lastUpdated: '2026-05-30T00:00:00Z',
  },
  {
    id: 'funder-schmidt-futures',
    name: 'Schmidt Futures',
    type: 'foundation',
    ein: '82-2806610',
    givingHistory: [
      { year: 2023, totalGiving: 250000000, grantsCount: 100, averageGrantSize: 2500000 },
      { year: 2024, totalGiving: 275000000, grantsCount: 110, averageGrantSize: 2500000 },
      { year: 2025, totalGiving: 300000000, grantsCount: 120, averageGrantSize: 2500000 },
    ],
    focusAreas: ['AI and advanced computing', 'workforce development', 'scientific talent', 'public policy', 'education innovation'],
    geographicFocus: ['United States', 'Global'],
    typicalAwardRange: { min: 250000, max: 10000000 },
    applicationProcess: 'Schmidt Futures identifies partners through their networks. Some open calls on their website.',
    deadlines: 'Varies by call; check website for current opportunities',
    sourceUrls: ['https://schmidtfutures.com'],
    lastUpdated: '2026-05-30T00:00:00Z',
  },
  {
    id: 'funder-propublica',
    name: 'ProPublica',
    type: 'other',
    ein: '14-2007220',
    givingHistory: [
      { year: 2023, totalGiving: 0, grantsCount: 0, averageGrantSize: 0 },
      { year: 2024, totalGiving: 0, grantsCount: 0, averageGrantSize: 0 },
      { year: 2025, totalGiving: 0, grantsCount: 0, averageGrantSize: 0 },
    ],
    focusAreas: ['nonprofit data', 'investigative journalism', 'public interest data', '990 data access'],
    geographicFocus: ['United States'],
    typicalAwardRange: { min: 0, max: 0 },
    applicationProcess: 'ProPublica Nonprofit Explorer API is a data source, not a funder. Provides 990 data access for foundation research.',
    deadlines: 'N/A — data source',
    sourceUrls: ['https://projects.propublica.org/nonprofits/api'],
    lastUpdated: '2026-05-30T00:00:00Z',
  },
];

export const SEED_SOURCES: Source[] = [
  {
    id: 'source-grants-gov',
    name: 'grants.gov',
    url: 'https://grants.gov',
    type: 'website',
    createdAt: '2026-05-30T00:00:00Z',
    isActive: true,
    category: 'government',
    sourceCrawlState: 'never-crawled',
    crawlAccessCategory: 'crawlable',
  },
  {
    id: 'source-nsf-gov',
    name: 'nsf.gov',
    url: 'https://nsf.gov',
    type: 'website',
    createdAt: '2026-05-30T00:00:00Z',
    isActive: true,
    category: 'government',
    sourceCrawlState: 'never-crawled',
    crawlAccessCategory: 'crawlable',
  },
  {
    id: 'source-google-org',
    name: 'google.org',
    url: 'https://google.org',
    type: 'website',
    createdAt: '2026-05-30T00:00:00Z',
    isActive: true,
    category: 'corporate',
    sourceCrawlState: 'never-crawled',
    crawlAccessCategory: 'crawlable',
  },
  {
    id: 'source-knight-foundation',
    name: 'knightfoundation.org',
    url: 'https://knightfoundation.org',
    type: 'website',
    createdAt: '2026-05-30T00:00:00Z',
    isActive: true,
    category: 'foundation',
    sourceCrawlState: 'never-crawled',
    crawlAccessCategory: 'crawlable',
  },
  {
    id: 'source-sloan-org',
    name: 'sloan.org',
    url: 'https://sloan.org',
    type: 'website',
    createdAt: '2026-05-30T00:00:00Z',
    isActive: true,
    category: 'foundation',
    sourceCrawlState: 'never-crawled',
    crawlAccessCategory: 'crawlable',
  },
  {
    id: 'source-schmidt-futures',
    name: 'schmidtfutures.com',
    url: 'https://schmidtfutures.com',
    type: 'website',
    createdAt: '2026-05-30T00:00:00Z',
    isActive: true,
    category: 'foundation',
    sourceCrawlState: 'never-crawled',
    crawlAccessCategory: 'crawlable',
  },
  {
    id: 'source-propublica-api',
    name: 'propublica.org/api',
    url: 'https://projects.propublica.org/nonprofits/api',
    type: 'api',
    createdAt: '2026-05-30T00:00:00Z',
    isActive: true,
    category: 'other',
    sourceCrawlState: 'never-crawled',
    crawlAccessCategory: 'crawlable',
  },
  {
    id: 'source-ca-grants',
    name: 'California Grants Portal',
    url: 'https://grants.ca.gov',
    type: 'website',
    createdAt: '2026-05-30T00:00:00Z',
    isActive: true,
    category: 'government',
    sourceCrawlState: 'never-crawled',
    crawlAccessCategory: 'crawlable',
  },
];

export const SEED_SCHEDULES: CrawlSchedule[] = [
  { id: 'sched-grants-gov', sourceId: 'source-grants-gov', intervalHours: 24, nextScheduledAt: new Date().toISOString(), isEnabled: true, createdAt: '2026-05-30T00:00:00Z' },
  { id: 'sched-nsf-gov', sourceId: 'source-nsf-gov', intervalHours: 48, nextScheduledAt: new Date().toISOString(), isEnabled: true, createdAt: '2026-05-30T00:00:00Z' },
  { id: 'sched-google-org', sourceId: 'source-google-org', intervalHours: 168, nextScheduledAt: new Date().toISOString(), isEnabled: true, createdAt: '2026-05-30T00:00:00Z' },
  { id: 'sched-knight', sourceId: 'source-knight-foundation', intervalHours: 168, nextScheduledAt: new Date().toISOString(), isEnabled: true, createdAt: '2026-05-30T00:00:00Z' },
  { id: 'sched-sloan', sourceId: 'source-sloan-org', intervalHours: 168, nextScheduledAt: new Date().toISOString(), isEnabled: true, createdAt: '2026-05-30T00:00:00Z' },
  { id: 'sched-schmidt', sourceId: 'source-schmidt-futures', intervalHours: 168, nextScheduledAt: new Date().toISOString(), isEnabled: true, createdAt: '2026-05-30T00:00:00Z' },
  { id: 'sched-propublica', sourceId: 'source-propublica-api', intervalHours: 24, nextScheduledAt: new Date().toISOString(), isEnabled: true, createdAt: '2026-05-30T00:00:00Z' },
  { id: 'sched-ca-grants', sourceId: 'source-ca-grants', intervalHours: 168, nextScheduledAt: new Date().toISOString(), isEnabled: true, createdAt: '2026-05-30T00:00:00Z' },
];
