import type { Grant, OrganizationProfile, Source } from './types';

const SEED_TIMESTAMP = '2026-05-01T00:00:00.000Z';

function buildFitRubric(score: number, dimensions: {
  missionAlignment: number;
  geographicFocus: number;
  programTrackrecord: number;
  budgetCapacity: number;
  partnershipReadiness: number;
}): NonNullable<Grant['fitRubric']> {
  return {
    missionAlignment: {
      score: dimensions.missionAlignment,
      justification: `Mission alignment: ${score} — supports Hacker Dojo's mission.`,
    },
    geographicFocus: {
      score: dimensions.geographicFocus,
      justification: `Geographic focus: ${score} — Bay Area / regional fit.`,
    },
    programTrackrecord: {
      score: dimensions.programTrackrecord,
      justification: `Program track record: ${score} — strong past delivery.`,
    },
    budgetCapacity: {
      score: dimensions.budgetCapacity,
      justification: `Budget capacity: ${score} — within Hacker Dojo's $25K-$250K band.`,
    },
    partnershipReadiness: {
      score: dimensions.partnershipReadiness,
      justification: `Partnership readiness: ${score} — leverages existing partnerships.`,
    },
    overallRationale: `Overall fit ${score} for Hacker Dojo.`,
    rubricVersion: 1,
  };
}

export const testFixtureGrants: Grant[] = [
  {
    id: 'nsf-techaccess',
    title: 'NSF Technology Access Workforce Grant',
    funder: 'National Science Foundation',
    funderShort: 'NSF',
    award: '$350,000',
    awardSort: 350000,
    deadline: '2026-06-15',
    deadlineConfidence: 'exact',
    daysOut: 16,
    fit: 88,
    tags: ['Federal', 'STEM Education'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 90,
      geographicFocus: 85,
      programTrackrecord: 88,
      budgetCapacity: 92,
      partnershipReadiness: 85,
    },
    fitRubric: buildFitRubric(88, {
      missionAlignment: 90,
      geographicFocus: 85,
      programTrackrecord: 88,
      budgetCapacity: 92,
      partnershipReadiness: 85,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'NSF funds transformative STEM education and workforce initiatives.',
    sourceCount: 1,
  },
  {
    id: 'fcc-stem',
    title: 'FCC Digital Equity & STEM Pathways',
    funder: 'Federal Communications Commission',
    funderShort: 'FCC',
    award: '$300,000',
    awardSort: 300000,
    deadline: '2026-06-09',
    deadlineConfidence: 'exact',
    daysOut: 10,
    fit: 86,
    tags: ['Federal', 'Community'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 88,
      geographicFocus: 84,
      programTrackrecord: 86,
      budgetCapacity: 90,
      partnershipReadiness: 83,
    },
    fitRubric: buildFitRubric(86, {
      missionAlignment: 88,
      geographicFocus: 84,
      programTrackrecord: 86,
      budgetCapacity: 90,
      partnershipReadiness: 83,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'FCC promotes digital equity and broadband access through education grants.',
    sourceCount: 1,
  },
  {
    id: 'morrell-edu',
    title: 'Morrell Foundation Education Initiative',
    funder: 'Morrell Foundation',
    funderShort: 'Morrell',
    award: '$50,000',
    awardSort: 50000,
    deadline: '2026-06-12',
    deadlineConfidence: 'exact',
    daysOut: 13,
    fit: 84,
    tags: ['Foundation', 'Education'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 86,
      geographicFocus: 82,
      programTrackrecord: 85,
      budgetCapacity: 80,
      partnershipReadiness: 87,
    },
    fitRubric: buildFitRubric(84, {
      missionAlignment: 86,
      geographicFocus: 82,
      programTrackrecord: 85,
      budgetCapacity: 80,
      partnershipReadiness: 87,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'Morrell Foundation supports educational equity and access programs.',
    sourceCount: 1,
  },
  {
    id: 'sv-community-fdn',
    title: 'Silicon Valley Community Foundation Community Impact Grant',
    funder: 'Silicon Valley Community Foundation',
    funderShort: 'SVCF',
    award: '$75,000',
    awardSort: 75000,
    deadline: 'Rolling',
    deadlineConfidence: 'rolling',
    daysOut: 999,
    fit: 82,
    tags: ['Foundation', 'Community'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 84,
      geographicFocus: 90,
      programTrackrecord: 82,
      budgetCapacity: 78,
      partnershipReadiness: 80,
    },
    fitRubric: buildFitRubric(82, {
      missionAlignment: 84,
      geographicFocus: 90,
      programTrackrecord: 82,
      budgetCapacity: 78,
      partnershipReadiness: 80,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'SVCF provides grants to strengthen communities across Silicon Valley.',
    sourceCount: 1,
  },
  {
    id: 'horizon-grants',
    title: 'Horizon Grants Innovation Fund',
    funder: 'Horizon Grants Foundation',
    funderShort: 'Horizon',
    award: '$90,000',
    awardSort: 90000,
    deadline: '2026-06-14',
    deadlineConfidence: 'exact',
    daysOut: 15,
    fit: 80,
    tags: ['Foundation', 'Science & Tech'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 82,
      geographicFocus: 78,
      programTrackrecord: 81,
      budgetCapacity: 76,
      partnershipReadiness: 83,
    },
    fitRubric: buildFitRubric(80, {
      missionAlignment: 82,
      geographicFocus: 78,
      programTrackrecord: 81,
      budgetCapacity: 76,
      partnershipReadiness: 83,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'Horizon Grants funds innovation and technology education programs.',
    sourceCount: 1,
  },
  {
    id: 'google-cs-first',
    title: 'Google CS First Community Grant',
    funder: 'Google.org',
    funderShort: 'Google',
    award: '$100,000',
    awardSort: 100000,
    deadline: '2026-06-30',
    deadlineConfidence: 'exact',
    daysOut: 31,
    fit: 79,
    tags: ['EdTech', 'STEM Education'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 81,
      geographicFocus: 77,
      programTrackrecord: 80,
      budgetCapacity: 75,
      partnershipReadiness: 82,
    },
    fitRubric: buildFitRubric(79, {
      missionAlignment: 81,
      geographicFocus: 77,
      programTrackrecord: 80,
      budgetCapacity: 75,
      partnershipReadiness: 82,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'Google.org supports computer science education and digital skills programs.',
    sourceCount: 1,
  },
  {
    id: 'united-way-grant',
    title: 'United Way Community Partnership Grant',
    funder: 'United Way Worldwide',
    funderShort: 'United Way',
    award: '$40,000',
    awardSort: 40000,
    deadline: '2026-06-05',
    deadlineConfidence: 'exact',
    daysOut: 6,
    fit: 78,
    tags: ['Foundation', 'Community'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 80,
      geographicFocus: 76,
      programTrackrecord: 79,
      budgetCapacity: 74,
      partnershipReadiness: 81,
    },
    fitRubric: buildFitRubric(78, {
      missionAlignment: 80,
      geographicFocus: 76,
      programTrackrecord: 79,
      budgetCapacity: 74,
      partnershipReadiness: 81,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'United Way funds community-based education and health initiatives.',
    sourceCount: 1,
  },
  {
    id: 'stanford-ed',
    title: 'Stanford Education Outreach Grant',
    funder: 'Stanford University',
    funderShort: 'Stanford',
    award: '$60,000',
    awardSort: 60000,
    deadline: '2026-06-20',
    deadlineConfidence: 'exact',
    daysOut: 21,
    fit: 77,
    tags: ['Foundation', 'Education'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 79,
      geographicFocus: 88,
      programTrackrecord: 77,
      budgetCapacity: 73,
      partnershipReadiness: 78,
    },
    fitRubric: buildFitRubric(77, {
      missionAlignment: 79,
      geographicFocus: 88,
      programTrackrecord: 77,
      budgetCapacity: 73,
      partnershipReadiness: 78,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'Stanford provides education outreach and community partnership grants.',
    sourceCount: 1,
  },
  {
    id: 'dell-equality',
    title: 'Dell Technologies Equality Fund',
    funder: 'Dell Technologies',
    funderShort: 'Dell',
    award: '$150,000',
    awardSort: 150000,
    deadline: '2026-07-01',
    deadlineConfidence: 'exact',
    daysOut: 32,
    fit: 76,
    tags: ['Corporate'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 78,
      geographicFocus: 74,
      programTrackrecord: 77,
      budgetCapacity: 72,
      partnershipReadiness: 79,
    },
    fitRubric: buildFitRubric(76, {
      missionAlignment: 78,
      geographicFocus: 74,
      programTrackrecord: 77,
      budgetCapacity: 72,
      partnershipReadiness: 79,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'Dell Technologies Equality Fund supports digital inclusion and STEM equity.',
    sourceCount: 1,
  },
  {
    id: 'mellon-arts',
    title: 'Mellon Foundation Arts & Humanities Grant',
    funder: 'Andrew W. Mellon Foundation',
    funderShort: 'Mellon',
    award: '$175,000',
    awardSort: 175000,
    deadline: '2026-07-25',
    deadlineConfidence: 'exact',
    daysOut: 56,
    fit: 73,
    tags: ['Foundation', 'EdTech'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 75,
      geographicFocus: 71,
      programTrackrecord: 74,
      budgetCapacity: 69,
      partnershipReadiness: 76,
    },
    fitRubric: buildFitRubric(73, {
      missionAlignment: 75,
      geographicFocus: 71,
      programTrackrecord: 74,
      budgetCapacity: 69,
      partnershipReadiness: 76,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'Mellon Foundation supports arts, humanities, and educational innovation.',
    sourceCount: 1,
  },
  {
    id: 'kresge-space',
    title: 'Kresge Foundation Creative Placemaking Grant',
    funder: 'Kresge Foundation',
    funderShort: 'Kresge',
    award: '$200,000',
    awardSort: 200000,
    deadline: '2026-08-15',
    deadlineConfidence: 'exact',
    daysOut: 77,
    fit: 71,
    tags: ['Foundation', 'Community'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 73,
      geographicFocus: 69,
      programTrackrecord: 72,
      budgetCapacity: 67,
      partnershipReadiness: 74,
    },
    fitRubric: buildFitRubric(71, {
      missionAlignment: 73,
      geographicFocus: 69,
      programTrackrecord: 72,
      budgetCapacity: 67,
      partnershipReadiness: 74,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'Kresge Foundation supports creative placemaking and community development.',
    sourceCount: 1,
  },
  {
    id: 'wwf-stem-equity',
    title: 'WWF STEM Equity in Conservation Grant',
    funder: 'World Wildlife Fund',
    funderShort: 'WWF',
    award: '$125,000',
    awardSort: 125000,
    deadline: '2026-07-15',
    deadlineConfidence: 'exact',
    daysOut: 46,
    fit: 68,
    tags: ['Science & Tech', 'EdTech'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 70,
      geographicFocus: 66,
      programTrackrecord: 69,
      budgetCapacity: 64,
      partnershipReadiness: 71,
    },
    fitRubric: buildFitRubric(68, {
      missionAlignment: 70,
      geographicFocus: 66,
      programTrackrecord: 69,
      budgetCapacity: 64,
      partnershipReadiness: 71,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'WWF supports environmental STEM education and conservation equity programs.',
    sourceCount: 1,
  },
  {
    id: 'dea-grant',
    title: 'DEA Youth Education Prevention Grant',
    funder: 'Drug Enforcement Administration',
    funderShort: 'DEA',
    award: '$30,000',
    awardSort: 30000,
    deadline: '2026-06-02',
    deadlineConfidence: 'exact',
    daysOut: 3,
    fit: 65,
    tags: ['Federal', 'Community'],
    status: 'matched',
    statusLabel: 'Matched',
    matchedAt: SEED_TIMESTAMP,
    fitBreakdown: {
      missionAlignment: 67,
      geographicFocus: 63,
      programTrackrecord: 66,
      budgetCapacity: 61,
      partnershipReadiness: 68,
    },
    fitRubric: buildFitRubric(65, {
      missionAlignment: 67,
      geographicFocus: 63,
      programTrackrecord: 66,
      budgetCapacity: 61,
      partnershipReadiness: 68,
    }),
    lastSeenAt: SEED_TIMESTAMP,
    lastUpdatedAt: SEED_TIMESTAMP,
    funderSummary: 'DEA provides youth education and prevention program grants.',
    sourceCount: 1,
  },
];

export const propublicaSourceFixture: Source = {
  id: 'propublica-default',
  name: 'ProPublica Nonprofit Explorer',
  url: 'https://projects.propublica.org/nonprofits/',
  type: 'api',
  createdAt: '2026-05-01T00:00:00.000Z',
  isActive: true,
  reviewStatus: 'approved',
  sourceCrawlState: 'never-crawled',
  crawlAccessCategory: 'crawlable',
  category: 'other',
  suggestedBy: 'system',
  suggestionReason: 'Hardcoded research source for ProPublica Nonprofit Explorer grant data',
};

export const testProfile: OrganizationProfile = {
  legalName: 'Hacker Dojo',
  ein: '26-3375350',
  samUEI: 'XK7N4HQ2P3M9',
  nonprofitStatus: '501(c)(3)',
  yearFounded: 2009,
  contactInfo: {
    email: 'ed@hackerdojo.com',
    website: 'https://hackerdojo.com',
  },
  geography: 'Silicon Valley, CA',
  mission: 'Community innovation and education with maker pathways.',
  programAreas: ['STEM Education', 'Community Innovation'],
  populationsServed: ['adults', 'youth'],
  fundingHistory: [],
  partnerships: [],
  complianceFacts: [],
  boardMembers: [{ name: 'Emily Johnson', role: 'Board Member' }],
  docTypes: ['PDF'],
  searchThemes: ['EdTech', 'Community Innovation'],
  agentBehavior: {
    autoDraftThreshold: 75,
    submissionPolicy: 'Human approval required',
    notifyEmail: 'ed@hackerdojo.com',
    voiceAndTone: 'Plain-spoken, evidence-led.',
  },
};
